spring.application.name=StockTrading

spring.datasource.url=jdbc:mysql://localhost:3306/enter your schema name
spring.datasource.username=enter your db username
spring.datasource.password=enter your db password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
